# Generated by Django 4.1.7 on 2023-04-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('names', models.CharField(max_length=180)),
                ('phone_number', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=250)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('childs_class', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
