# Generated by Django 4.1.7 on 2023-04-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=400)),
                ('answer', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='images')),
                ('link', models.CharField(max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media',
            },
        ),
        migrations.CreateModel(
            name='IndexInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ImageField(null=True, upload_to='images')),
                ('brand_height', models.PositiveIntegerField(null=True)),
                ('welcome_img', models.ImageField(null=True, upload_to='images')),
                ('title1', models.CharField(max_length=200)),
                ('title2', models.CharField(max_length=200)),
                ('about_company', models.TextField()),
                ('product_title', models.CharField(max_length=200)),
                ('product_info', models.TextField()),
                ('terms', models.FileField(null=True, upload_to='files')),
                ('company_requisities', models.CharField(max_length=200, null=True)),
                ('footer_motto', models.CharField(max_length=300)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('media', models.ManyToManyField(to='lp.socialmedia')),
            ],
            options={
                'verbose_name': 'Index information',
                'verbose_name_plural': 'Index information',
            },
        ),
    ]
